"""
API payload structures for Portland self-service API.

This module contains the payload templates required by the Portland
EnerGov API. The API requires all criteria fields to be present in
the request, even if they are set to None.
"""

from enum import Enum


class LicenseType(Enum):
    """License types for different property categories."""

    MULTI_FAMILY = ("Multi Family", "ddf09feb-ce7d-4437-839d-33296fd1c849_c7f4be57-4935-461c-bcf1-8d89c7973b81")
    SINGLE_FAMILY = ("Single Family", "ddf09feb-ce7d-4437-839d-33296fd1c849_5c7dadf7-db4e-4d4d-a1fa-c109dbf3c0c5")
    TWO_FAMILY = ("Two Family", "ddf09feb-ce7d-4437-839d-33296fd1c849_0b3794bb-b86f-467c-b6c0-6d473a8c6966")

    def __init__(self, display_name: str, type_id: str) -> None:
        self.display_name = display_name
        self.type_id = type_id


def build_search_payload(license_type: LicenseType, page_number: int, page_size: int, issue_date_from: str) -> dict:
    """
    Build the complete search payload required by the Portland API.

    The API requires all criteria fields to be present, even when unused.
    This ensures we don't get a 500 error from missing fields.

    Args:
    license_type: LicenseType enum member
    page_number: Page number to retrieve (1-indexed)
    page_size: Number of results per page
    issue_date_from: ISO 8601 formatted date string for filtering licenses

    Returns:
    Complete payload dictionary for the search API

    """
    return {
        "Keyword": "",
        "ExactMatch": True,
        "SearchModule": 10,
        "FilterModule": 1,
        "SearchMainAddress": False,
        "PlanCriteria": {
            "PlanNumber": None,
            "PlanTypeId": None,
            "PlanWorkclassId": None,
            "PlanStatusId": None,
            "ProjectName": None,
            "ApplyDateFrom": None,
            "ApplyDateTo": None,
            "ExpireDateFrom": None,
            "ExpireDateTo": None,
            "CompleteDateFrom": None,
            "CompleteDateTo": None,
            "Address": None,
            "Description": None,
            "SearchMainAddress": False,
            "ContactId": None,
            "ParcelNumber": None,
            "TypeId": None,
            "WorkClassIds": None,
            "ExcludeCases": None,
            "EnableDescriptionSearch": False,
            "PageNumber": 0,
            "PageSize": 0,
            "SortBy": None,
            "SortAscending": False,
        },
        "PermitCriteria": {
            "PermitNumber": None,
            "PermitTypeId": None,
            "PermitWorkclassId": None,
            "PermitStatusId": None,
            "ProjectName": None,
            "IssueDateFrom": None,
            "IssueDateTo": None,
            "Address": None,
            "Description": None,
            "ExpireDateFrom": None,
            "ExpireDateTo": None,
            "FinalDateFrom": None,
            "FinalDateTo": None,
            "ApplyDateFrom": None,
            "ApplyDateTo": None,
            "SearchMainAddress": False,
            "ContactId": None,
            "TypeId": None,
            "WorkClassIds": None,
            "ParcelNumber": None,
            "ExcludeCases": None,
            "EnableDescriptionSearch": False,
            "PageNumber": 0,
            "PageSize": 0,
            "SortBy": None,
            "SortAscending": False,
        },
        "InspectionCriteria": {
            "Keyword": None,
            "ExactMatch": False,
            "Complete": None,
            "InspectionNumber": None,
            "InspectionTypeId": None,
            "InspectionStatusId": None,
            "RequestDateFrom": None,
            "RequestDateTo": None,
            "ScheduleDateFrom": None,
            "ScheduleDateTo": None,
            "Address": None,
            "SearchMainAddress": False,
            "ContactId": None,
            "TypeId": [],
            "WorkClassIds": [],
            "ParcelNumber": None,
            "DisplayCodeInspections": False,
            "ExcludeCases": [],
            "ExcludeFilterModules": [],
            "HiddenInspectionTypeIDs": None,
            "PageNumber": 0,
            "PageSize": 0,
            "SortBy": None,
            "SortAscending": False,
        },
        "CodeCaseCriteria": {
            "CodeCaseNumber": None,
            "CodeCaseTypeId": None,
            "CodeCaseStatusId": None,
            "ProjectName": None,
            "OpenedDateFrom": None,
            "OpenedDateTo": None,
            "ClosedDateFrom": None,
            "ClosedDateTo": None,
            "Address": None,
            "ParcelNumber": None,
            "Description": None,
            "SearchMainAddress": False,
            "RequestId": None,
            "ExcludeCases": None,
            "ContactId": None,
            "EnableDescriptionSearch": False,
            "PageNumber": 0,
            "PageSize": 0,
            "SortBy": None,
            "SortAscending": False,
        },
        "RequestCriteria": {
            "RequestNumber": None,
            "RequestTypeId": None,
            "RequestStatusId": None,
            "ProjectName": None,
            "EnteredDateFrom": None,
            "EnteredDateTo": None,
            "DeadlineDateFrom": None,
            "DeadlineDateTo": None,
            "CompleteDateFrom": None,
            "CompleteDateTo": None,
            "Address": None,
            "ParcelNumber": None,
            "SearchMainAddress": False,
            "PageNumber": 0,
            "PageSize": 0,
            "SortBy": None,
            "SortAscending": False,
        },
        "BusinessLicenseCriteria": {
            "LicenseNumber": None,
            "LicenseTypeId": None,
            "LicenseClassId": None,
            "LicenseStatusId": None,
            "BusinessStatusId": None,
            "LicenseYear": None,
            "ApplicationDateFrom": None,
            "ApplicationDateTo": None,
            "IssueDateFrom": None,
            "IssueDateTo": None,
            "ExpirationDateFrom": None,
            "ExpirationDateTo": None,
            "SearchMainAddress": False,
            "CompanyTypeId": None,
            "CompanyName": None,
            "BusinessTypeId": None,
            "Description": None,
            "CompanyOpenedDateFrom": None,
            "CompanyOpenedDateTo": None,
            "CompanyClosedDateFrom": None,
            "CompanyClosedDateTo": None,
            "LastAuditDateFrom": None,
            "LastAuditDateTo": None,
            "ParcelNumber": None,
            "Address": None,
            "TaxID": None,
            "DBA": None,
            "ExcludeCases": None,
            "TypeId": None,
            "WorkClassIds": None,
            "ContactId": None,
            "PageNumber": 0,
            "PageSize": 0,
            "SortBy": None,
            "SortAscending": False,
        },
        "ProfessionalLicenseCriteria": {
            "LicenseNumber": None,
            "HolderFirstName": None,
            "HolderMiddleName": None,
            "HolderLastName": None,
            "HolderCompanyName": None,
            "LicenseTypeId": None,
            "LicenseClassId": None,
            "LicenseStatusId": None,
            "IssueDateFrom": None,
            "IssueDateTo": None,
            "ExpirationDateFrom": None,
            "ExpirationDateTo": None,
            "ApplicationDateFrom": None,
            "ApplicationDateTo": None,
            "Address": None,
            "MainParcel": None,
            "SearchMainAddress": False,
            "ExcludeCases": None,
            "TypeId": None,
            "WorkClassIds": None,
            "ContactId": None,
            "PageNumber": 0,
            "PageSize": 0,
            "SortBy": None,
            "SortAscending": False,
        },
        "LicenseCriteria": {
            "LicenseNumber": None,
            "LicenseTypeId": license_type.type_id,
            "LicenseClassId": "none",
            "LicenseStatusId": "none",
            "BusinessStatusId": "none",
            "ApplicationDateFrom": None,
            "ApplicationDateTo": None,
            "IssueDateFrom": issue_date_from,
            "IssueDateTo": None,
            "ExpirationDateFrom": None,
            "ExpirationDateTo": None,
            "SearchMainAddress": False,
            "CompanyTypeId": "none",
            "CompanyName": None,
            "BusinessTypeId": "none",
            "Description": None,
            "CompanyOpenedDateFrom": None,
            "CompanyOpenedDateTo": None,
            "CompanyClosedDateFrom": None,
            "CompanyClosedDateTo": None,
            "LastAuditDateFrom": None,
            "LastAuditDateTo": None,
            "ParcelNumber": None,
            "Address": None,
            "TaxID": None,
            "DBA": None,
            "ExcludeCases": None,
            "TypeId": None,
            "WorkClassIds": None,
            "ContactId": None,
            "HolderFirstName": None,
            "HolderMiddleName": None,
            "HolderLastName": None,
            "MainParcel": None,
            "EnableDescriptionSearchForBLicense": False,
            "EnableDescriptionSearchForPLicense": False,
            "PageNumber": page_number,
            "PageSize": page_size,
            "SortBy": "relevance",
            "SortAscending": False,
        },
        "ProjectCriteria": {
            "ProjectNumber": None,
            "ProjectName": None,
            "Address": None,
            "ParcelNumber": None,
            "StartDateFrom": None,
            "StartDateTo": None,
            "ExpectedEndDateFrom": None,
            "ExpectedEndDateTo": None,
            "CompleteDateFrom": None,
            "CompleteDateTo": None,
            "Description": None,
            "SearchMainAddress": False,
            "ContactId": None,
            "TypeId": None,
            "ExcludeCases": None,
            "EnableDescriptionSearch": False,
            "PageNumber": 0,
            "PageSize": 0,
            "SortBy": None,
            "SortAscending": False,
        },
        "LicenseSortList": [
            {"Key": "relevance", "Value": "Relevance"},
            {"Key": "LicenseNumber.keyword", "Value": "License Number"},
            {"Key": "CompanyName.keyword", "Value": "Company Name"},
            {"Key": "AppliedDate", "Value": "Applied Date"},
            {"Key": "MainAddress", "Value": "Address"},
        ],
        "ExcludeCases": None,
        "SortOrderList": [
            {"Key": True, "Value": "Ascending"},
            {"Key": False, "Value": "Descending"},
        ],
        "HiddenInspectionTypeIDs": None,
        "PageNumber": 0,
        "PageSize": 0,
        "SortBy": "relevance",
        "SortAscending": True,
    }
